brokerid: "{{ inventory_hostname | regex_search('(dj-kafka0[1-9]\\.foo\\.bar)') | regex_replace('\\.foo\\.bar', '') | regex_replace('^dj-kafka0', '') }}"
zookeeperinfo: dj-zk01.foo.bar:2181,dj-zk02.foo.bar:2181,dj-zk03.foo.bar:2181
dir_path: /data/kafka-logs