---
- hosts: kafkahosts
  become: true
  connection: ssh
  vars:
    - zookeeperinfo: dj-zk01.foo.bar:2181,dj-zk02.foo.bar:2181,dj-zk03.foo.bar:2181/kafka1
    - dir_path: /data/kafka1-logs
  roles:
    - common
    - kafka