all:
  hosts:
    dj-zk01:
      ansible_host: dj-zk01.foo.bar
    dj-zk02:
      ansible_host: dj-zk02.foo.bar
    dj-zk03:
      ansible_host: dj-zk03.foo.bar
    dj-kafka01:
      ansible_host: dj-kafka01.foo.bar
    dj-kafka02:
      ansible_host: dj-kafka02.foo.bar
    dj-kafka03:
      ansible_host: dj-kafka03.foo.bar
  vars:
    ansible_user: ec2-user
    ansible_become: yes
    ansible_ssh_private_key_file: /home/ec2-user/.ssh/dev.pem
  children:
    zkhosts:
      hosts:
        dj-zk[01:03].foo.bar
    kafkahosts:
      hosts:
        dj-kafka[01:03].foo.bar
    kerberoshosts:
      hosts:
        dj-zk01.foo.bar